name: Build and test lab-cicd

on:
  # Automatically run this pipeline on every push to the main branch
  push:
    branches:
      - main
  # Allow running this pipeline manually from githubs website.
  workflow_dispatch:

jobs:
  test:
    # Run on a ubuntu-22.04 VM image
    runs-on: ubuntu-22.04
    name: Test cicd-lab
    steps:
      # Checkout our repository
      - uses: actions/checkout@v3

      # Install our NPM dependencies
      - name: Install dependencies
        run: npm ci

      # Run our unit tests
      - name: Run unit tests
        run: npm run test
  build:
    # Run on a ubuntu-22.04 VM image
    runs-on: ubuntu-22.04
    permissions:
    packages: write
    contents: read
    name: Build cicd-lab
    env:
      GITHUB_USER: <YOUR_USER>
      IMAGE_REGISTRY: ghcr.io/<YOUR_USER>
    steps:
      # Checkout our repository
      - uses: actions/checkout@v3

      # Setup Docker with BuildKit (faster builds and cache support)
      - uses: docker/setup-buildx-action@v2

      # Login to our container registry at ghcr.io/YOUR_USER with our credentials
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: "${{ env.IMAGE_REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"

      # Some environment variables to not have to retype the same thing all the time.
      - name: Set environment variables
        run: |
          # Use a sha as version
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Build and push our container image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          # Name our container image ghcr.io/YOUR_USER/lab-cicd:latest and something similar to ghcr.io/YOUR_USER/lab-cicd:f296f4d
          tags: "${{ env.IMAGE_REGISTRY }}/lab-cicd:${{ env.SHA_SHORT }},${{ env.IMAGE_REGISTRY }}/lab-cicd:latest"
